name: ${project.name}
version: ${project.version}-SILENCY
description: ${project.description}
authors: [cereal, Sleaker, mung3r, LinuxServer]
website: ${project.url}
api-version: 1.21

main: ${mainClass}
load: startup

commands:
  vault-info:
    description: Displays information about Vault 
    usage: |
           /<command> - Displays Vault information
    permission: vault.admin
permissions:
  vault.admin:
    description: Notifies the player when vault is in need of an update.
    default: op